# Generated by Django 5.2.5 on 2025-08-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
